name: Push_GitLab

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push update to inpt repo
        env:
          token: ${{ secrets.SSH_PRIVATE_KEY}}
        run: |
          echo Starting to push repo to gitlab
          git config user.name "tkn7092"
          git config user.email "timothee.klein@etu.inp-n7.fr"
          git remote set-url origin "https://oauth2:${token}@git.inpt.fr/kleint/N7.git"
          git filter-branch -- --all
          git push origin main --force
